version: '3.7'

# Define services
services:
  # Frontend Service 
  app:
    build: 
      context: ./studydevops
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: react-container
    ports:
     # Host port:Container port
      - '8081:8081'
    stdin_open: true
    
