name: project react ui cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build react
        run: |
          npm install
      - name: Github login
        run: |
          docker login --username balo282 --password-stdin ${{ secrets.GITHUB_TOKEN }} ghcr.io
#          docker login --username balo282 --password-stdin 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 ghcr.io
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/paduxe/helloworld-ui-images:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/paduxe/helloworld-ui-images:latest
      - name: Create mnt-ui folder and run docker compose
        run: |
          mkdir -p /mnt-ui/studydevops/
          mv docker-compose.yml /mnt-ui/studydevops/
          pwd
          cd /mnt-ui/studydevops/
          pwd
          ls -a
          docker ps
          echo 'start docker compose up'
          docker-compose up -d
