name: project react client cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Github login
        run: |
          docker login --username balo282 --password ${{ secrets.GH_TOKEN }} ghcr.io
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/paduxe/react-ui-images:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/paduxe/react-ui-images:latest
      - name: Create mnt folder and run docker compose
        run: |
          mkdir -p /mnt/react-ui/
          mv docker-compose.yml /mnt/react-ui/
          pwd
          cd /mnt/react-ui/
          pwd
          ls -a
          docker ps
          docker-compose up -d
